// Code generated for stas-tsarev service
// © Stanislav Tsarev 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/stas-tsarev/dz1_order_service/inventory/internal/repository/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

type InventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryRepository) EXPECT() *InventoryRepository_Expecter {
	return &InventoryRepository_Expecter{mock: &_m.Mock}
}

// CreatePart provides a mock function with given fields: ctx, part
func (_m *InventoryRepository) CreatePart(ctx context.Context, part model.PartInfo) (string, error) {
	ret := _m.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for CreatePart")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartInfo) (string, error)); ok {
		return rf(ctx, part)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartInfo) string); ok {
		r0 = rf(ctx, part)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartInfo) error); ok {
		r1 = rf(ctx, part)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_CreatePart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePart'
type InventoryRepository_CreatePart_Call struct {
	*mock.Call
}

// CreatePart is a helper method to define mock.On call
//   - ctx context.Context
//   - part model.PartInfo
func (_e *InventoryRepository_Expecter) CreatePart(ctx interface{}, part interface{}) *InventoryRepository_CreatePart_Call {
	return &InventoryRepository_CreatePart_Call{Call: _e.mock.On("CreatePart", ctx, part)}
}

func (_c *InventoryRepository_CreatePart_Call) Run(run func(ctx context.Context, part model.PartInfo)) *InventoryRepository_CreatePart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartInfo))
	})
	return _c
}

func (_c *InventoryRepository_CreatePart_Call) Return(_a0 string, _a1 error) *InventoryRepository_CreatePart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_CreatePart_Call) RunAndReturn(run func(context.Context, model.PartInfo) (string, error)) *InventoryRepository_CreatePart_Call {
	_c.Call.Return(run)
	return _c
}

// GetPart provides a mock function with given fields: ctx, uuid
func (_m *InventoryRepository) GetPart(ctx context.Context, uuid string) (model.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryRepository_Expecter) GetPart(ctx interface{}, uuid interface{}) *InventoryRepository_GetPart_Call {
	return &InventoryRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuid)}
}

func (_c *InventoryRepository_GetPart_Call) Run(run func(ctx context.Context, uuid string)) *InventoryRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryRepository_GetPart_Call) Return(_a0 model.Part, _a1 error) *InventoryRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_GetPart_Call) RunAndReturn(run func(context.Context, string) (model.Part, error)) *InventoryRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *InventoryRepository) ListParts(ctx context.Context, filter *model.PartsFilter) ([]model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) ([]model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.PartsFilter
func (_e *InventoryRepository_Expecter) ListParts(ctx interface{}, filter interface{}) *InventoryRepository_ListParts_Call {
	return &InventoryRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *InventoryRepository_ListParts_Call) Run(run func(ctx context.Context, filter *model.PartsFilter)) *InventoryRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PartsFilter))
	})
	return _c
}

func (_c *InventoryRepository_ListParts_Call) Return(_a0 []model.Part, _a1 error) *InventoryRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_ListParts_Call) RunAndReturn(run func(context.Context, *model.PartsFilter) ([]model.Part, error)) *InventoryRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
