// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventory_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Category описывает виды деталей
type Category int32

const (
	Category_CATEGORY_UNKNOWN_UNSPECIFIED Category = 0 // Неизвестная категория
	Category_CATEGORY_ENGINE              Category = 1 // Двигатель
	Category_CATEGORY_FUEL                Category = 2 // Топливо
	Category_CATEGORY_PORTHOLE            Category = 3 // Иллюминатор
	Category_CATEGORY_WING                Category = 4 // Крыло
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNKNOWN_UNSPECIFIED",
		1: "CATEGORY_ENGINE",
		2: "CATEGORY_FUEL",
		3: "CATEGORY_PORTHOLE",
		4: "CATEGORY_WING",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNKNOWN_UNSPECIFIED": 0,
		"CATEGORY_ENGINE":              1,
		"CATEGORY_FUEL":                2,
		"CATEGORY_PORTHOLE":            3,
		"CATEGORY_WING":                4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// Part без uuid, необходим для Create
type PartInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Название детали
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                                     // Описание детали
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`                                                                               // Цена за единицу
	StockQuantity int64                  `protobuf:"varint,4,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`                                           // Количество на складе
	Category      Category               `protobuf:"varint,5,opt,name=category,proto3,enum=inventory.v1.Category" json:"category,omitempty"`                                               // Категория
	Dimensions    *Dimensions            `protobuf:"bytes,6,opt,name=dimensions,proto3" json:"dimensions,omitempty"`                                                                       // Размеры детали
	Manufacturer  *Manufacturer          `protobuf:"bytes,7,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`                                                                   // Информация о производителе
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                   // Теги для быстрого поиска
	Metadata      map[string]*Value      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Гибкие метаданные
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartInfo) Reset() {
	*x = PartInfo{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartInfo) ProtoMessage() {}

func (x *PartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartInfo.ProtoReflect.Descriptor instead.
func (*PartInfo) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *PartInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PartInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PartInfo) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *PartInfo) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNKNOWN_UNSPECIFIED
}

func (x *PartInfo) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *PartInfo) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *PartInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PartInfo) GetMetadata() map[string]*Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Part содержит в себе информацию о детали
type Part struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // Идентификатор детали
	Info          *PartInfo              `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`                            // Информация о детали
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Дата обновления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetInfo() *PartInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Part) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Dimensions для описания размеров детали
type Dimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        float64                `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"` // Длина в см
	Width         float64                `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`   // Ширина в см
	Height        float64                `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"` // Высота в см
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"` // Вес в кг
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Dimensions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Dimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Dimensions) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// Manufacturer для описания производителя
type Manufacturer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // Название
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"` // Страна производителя
	Website       string                 `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"` // Сайт производителя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Manufacturer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

// Value необходим для метаданных
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringValue   string                 `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	Int64Value    int64                  `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	DoubleValue   float64                `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	BoolValue     bool                   `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *Value) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

// PartsFilter нужен для поиска деталей по фильтру
type PartsFilter struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Uuids                 []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Names                 []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Categories            []Category             `protobuf:"varint,3,rep,packed,name=categories,proto3,enum=inventory.v1.Category" json:"categories,omitempty"`
	ManufacturerCountries []string               `protobuf:"bytes,4,rep,name=manufacturer_countries,json=manufacturerCountries,proto3" json:"manufacturer_countries,omitempty"`
	Tags                  []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PartsFilter) Reset() {
	*x = PartsFilter{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartsFilter) ProtoMessage() {}

func (x *PartsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartsFilter.ProtoReflect.Descriptor instead.
func (*PartsFilter) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *PartsFilter) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *PartsFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PartsFilter) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PartsFilter) GetManufacturerCountries() []string {
	if x != nil {
		return x.ManufacturerCountries
	}
	return nil
}

func (x *PartsFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Запрос для получения информации о детали по ее uuid
type GetPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Идентификатор детали
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *GetPartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Ответ, содержащий иформацию о детали по ее uuid
type GetPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Part          *Part                  `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"` // Информация о детали
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartResponse) Reset() {
	*x = GetPartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartResponse) ProtoMessage() {}

func (x *GetPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartResponse.ProtoReflect.Descriptor instead.
func (*GetPartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *GetPartResponse) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

// Запрос для получения информации о деталях с указанными параметрами
type ListPartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *PartsFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"` // Фильтр по деталям
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsRequest) Reset() {
	*x = ListPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsRequest) ProtoMessage() {}

func (x *ListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsRequest.ProtoReflect.Descriptor instead.
func (*ListPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ListPartsRequest) GetFilter() *PartsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Ответ, содержащий информацию о деталях с указанными параметрами
type ListPartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*Part                `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"` // Список найденных деталей
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsResponse) Reset() {
	*x = ListPartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsResponse) ProtoMessage() {}

func (x *ListPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsResponse.ProtoReflect.Descriptor instead.
func (*ListPartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ListPartsResponse) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

// Запрос на создание детали
type CreatePartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PartInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // Информация о детали
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartRequest) Reset() {
	*x = CreatePartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartRequest) ProtoMessage() {}

func (x *CreatePartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartRequest.ProtoReflect.Descriptor instead.
func (*CreatePartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePartRequest) GetInfo() *PartInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// Ответ на создание детали
type CreatePartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Идентификатор созданной детали
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartResponse) Reset() {
	*x = CreatePartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartResponse) ProtoMessage() {}

func (x *CreatePartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartResponse.ProtoReflect.Descriptor instead.
func (*CreatePartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePartResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x03\n" +
	"\bPartInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x04 \x01(\x03R\rstockQuantity\x122\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x16.inventory.v1.CategoryR\bcategory\x128\n" +
	"\n" +
	"dimensions\x18\x06 \x01(\v2\x18.inventory.v1.DimensionsR\n" +
	"dimensions\x12>\n" +
	"\fmanufacturer\x18\a \x01(\v2\x1a.inventory.v1.ManufacturerR\fmanufacturer\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.inventory.v1.PartInfo.MetadataEntryR\bmetadata\x1aP\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.inventory.v1.ValueR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x04Part\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\x04info\x18\x02 \x01(\v2\x16.inventory.v1.PartInfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"j\n" +
	"\n" +
	"Dimensions\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"V\n" +
	"\fManufacturer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\"\x8d\x01\n" +
	"\x05Value\x12!\n" +
	"\fstring_value\x18\x01 \x01(\tR\vstringValue\x12\x1f\n" +
	"\vint64_value\x18\x02 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fdouble_value\x18\x03 \x01(\x01R\vdoubleValue\x12\x1d\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bR\tboolValue\"\xbc\x01\n" +
	"\vPartsFilter\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x126\n" +
	"\n" +
	"categories\x18\x03 \x03(\x0e2\x16.inventory.v1.CategoryR\n" +
	"categories\x125\n" +
	"\x16manufacturer_countries\x18\x04 \x03(\tR\x15manufacturerCountries\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"$\n" +
	"\x0eGetPartRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"9\n" +
	"\x0fGetPartResponse\x12&\n" +
	"\x04part\x18\x01 \x01(\v2\x12.inventory.v1.PartR\x04part\"E\n" +
	"\x10ListPartsRequest\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.inventory.v1.PartsFilterR\x06filter\"=\n" +
	"\x11ListPartsResponse\x12(\n" +
	"\x05parts\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x05parts\"?\n" +
	"\x11CreatePartRequest\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.inventory.v1.PartInfoR\x04info\"(\n" +
	"\x12CreatePartResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid*~\n" +
	"\bCategory\x12 \n" +
	"\x1cCATEGORY_UNKNOWN_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCATEGORY_ENGINE\x10\x01\x12\x11\n" +
	"\rCATEGORY_FUEL\x10\x02\x12\x15\n" +
	"\x11CATEGORY_PORTHOLE\x10\x03\x12\x11\n" +
	"\rCATEGORY_WING\x10\x042\xf9\x01\n" +
	"\x10InventoryService\x12F\n" +
	"\aGetPart\x12\x1c.inventory.v1.GetPartRequest\x1a\x1d.inventory.v1.GetPartResponse\x12L\n" +
	"\tListParts\x12\x1e.inventory.v1.ListPartsRequest\x1a\x1f.inventory.v1.ListPartsResponse\x12O\n" +
	"\n" +
	"CreatePart\x12\x1f.inventory.v1.CreatePartRequest\x1a .inventory.v1.CreatePartResponseBVZThttps://github.com/stas-tsarev/dz1_order_service/pkg/proto/inventory/v1;inventory_v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(Category)(0),                 // 0: inventory.v1.Category
	(*PartInfo)(nil),              // 1: inventory.v1.PartInfo
	(*Part)(nil),                  // 2: inventory.v1.Part
	(*Dimensions)(nil),            // 3: inventory.v1.Dimensions
	(*Manufacturer)(nil),          // 4: inventory.v1.Manufacturer
	(*Value)(nil),                 // 5: inventory.v1.Value
	(*PartsFilter)(nil),           // 6: inventory.v1.PartsFilter
	(*GetPartRequest)(nil),        // 7: inventory.v1.GetPartRequest
	(*GetPartResponse)(nil),       // 8: inventory.v1.GetPartResponse
	(*ListPartsRequest)(nil),      // 9: inventory.v1.ListPartsRequest
	(*ListPartsResponse)(nil),     // 10: inventory.v1.ListPartsResponse
	(*CreatePartRequest)(nil),     // 11: inventory.v1.CreatePartRequest
	(*CreatePartResponse)(nil),    // 12: inventory.v1.CreatePartResponse
	nil,                           // 13: inventory.v1.PartInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.PartInfo.category:type_name -> inventory.v1.Category
	3,  // 1: inventory.v1.PartInfo.dimensions:type_name -> inventory.v1.Dimensions
	4,  // 2: inventory.v1.PartInfo.manufacturer:type_name -> inventory.v1.Manufacturer
	13, // 3: inventory.v1.PartInfo.metadata:type_name -> inventory.v1.PartInfo.MetadataEntry
	1,  // 4: inventory.v1.Part.info:type_name -> inventory.v1.PartInfo
	14, // 5: inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	14, // 6: inventory.v1.Part.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: inventory.v1.PartsFilter.categories:type_name -> inventory.v1.Category
	2,  // 8: inventory.v1.GetPartResponse.part:type_name -> inventory.v1.Part
	6,  // 9: inventory.v1.ListPartsRequest.filter:type_name -> inventory.v1.PartsFilter
	2,  // 10: inventory.v1.ListPartsResponse.parts:type_name -> inventory.v1.Part
	1,  // 11: inventory.v1.CreatePartRequest.info:type_name -> inventory.v1.PartInfo
	5,  // 12: inventory.v1.PartInfo.MetadataEntry.value:type_name -> inventory.v1.Value
	7,  // 13: inventory.v1.InventoryService.GetPart:input_type -> inventory.v1.GetPartRequest
	9,  // 14: inventory.v1.InventoryService.ListParts:input_type -> inventory.v1.ListPartsRequest
	11, // 15: inventory.v1.InventoryService.CreatePart:input_type -> inventory.v1.CreatePartRequest
	8,  // 16: inventory.v1.InventoryService.GetPart:output_type -> inventory.v1.GetPartResponse
	10, // 17: inventory.v1.InventoryService.ListParts:output_type -> inventory.v1.ListPartsResponse
	12, // 18: inventory.v1.InventoryService.CreatePart:output_type -> inventory.v1.CreatePartResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
