// Code generated for stas-tsarev service
// © Stanislav Tsarev 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/stas-tsarev/dz1_order_service/order/internal/repository/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, orderUuid
func (_m *OrderRepository) CancelOrder(ctx context.Context, orderUuid string) error {
	ret := _m.Called(ctx, orderUuid)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderRepository_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUuid string
func (_e *OrderRepository_Expecter) CancelOrder(ctx interface{}, orderUuid interface{}) *OrderRepository_CancelOrder_Call {
	return &OrderRepository_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderUuid)}
}

func (_c *OrderRepository_CancelOrder_Call) Run(run func(ctx context.Context, orderUuid string)) *OrderRepository_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) Return(_a0 error) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) RunAndReturn(run func(context.Context, string) error) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: _a0, userUuid, partUuids, totalPrice
func (_m *OrderRepository) CreateOrder(_a0 context.Context, userUuid string, partUuids []string, totalPrice float64) (string, float64, error) {
	ret := _m.Called(_a0, userUuid, partUuids, totalPrice)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 string
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, float64) (string, float64, error)); ok {
		return rf(_a0, userUuid, partUuids, totalPrice)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, float64) string); ok {
		r0 = rf(_a0, userUuid, partUuids, totalPrice)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, float64) float64); ok {
		r1 = rf(_a0, userUuid, partUuids, totalPrice)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []string, float64) error); ok {
		r2 = rf(_a0, userUuid, partUuids, totalPrice)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - _a0 context.Context
//   - userUuid string
//   - partUuids []string
//   - totalPrice float64
func (_e *OrderRepository_Expecter) CreateOrder(_a0 interface{}, userUuid interface{}, partUuids interface{}, totalPrice interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", _a0, userUuid, partUuids, totalPrice)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(_a0 context.Context, userUuid string, partUuids []string, totalPrice float64)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(float64))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 string, _a1 float64, _a2 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, string, []string, float64) (string, float64, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, orderUuid
func (_m *OrderRepository) GetOrder(ctx context.Context, orderUuid string) (model.Order, error) {
	ret := _m.Called(ctx, orderUuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, orderUuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, orderUuid)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUuid string
func (_e *OrderRepository_Expecter) GetOrder(ctx interface{}, orderUuid interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderUuid)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(ctx context.Context, orderUuid string)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(_a0 model.Order, _a1 error) *OrderRepository_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, orderUuid, paymentMethod, transactionUuid
func (_m *OrderRepository) PayOrder(ctx context.Context, orderUuid string, paymentMethod string, transactionUuid string) error {
	ret := _m.Called(ctx, orderUuid, paymentMethod, transactionUuid)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, orderUuid, paymentMethod, transactionUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderRepository_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUuid string
//   - paymentMethod string
//   - transactionUuid string
func (_e *OrderRepository_Expecter) PayOrder(ctx interface{}, orderUuid interface{}, paymentMethod interface{}, transactionUuid interface{}) *OrderRepository_PayOrder_Call {
	return &OrderRepository_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUuid, paymentMethod, transactionUuid)}
}

func (_c *OrderRepository_PayOrder_Call) Run(run func(ctx context.Context, orderUuid string, paymentMethod string, transactionUuid string)) *OrderRepository_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *OrderRepository_PayOrder_Call) Return(_a0 error) *OrderRepository_PayOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, string) error) *OrderRepository_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
