// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// UUID деталей для заказа.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// UUID созданного заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Общая стоимость заказа.
	TotalPrice float32 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float32 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/delete_order_request
type DeleteOrderRequest struct {
	// UUID отменяемого заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *DeleteOrderRequest) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// SetOrderUUID sets the value of OrderUUID.
func (s *DeleteOrderRequest) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// Ref: #/components/schemas/get_order_response
type GetOrderResponse struct {
	PaymentMethod Order `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderResponse) GetPaymentMethod() Order {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderResponse) SetPaymentMethod(val Order) {
	s.PaymentMethod = val
}

func (*GetOrderResponse) getOrderRes() {}

// NewNilUUID returns new NilUUID with value set to v.
func NewNilUUID(v uuid.UUID) NilUUID {
	return NilUUID{
		Value: v,
	}
}

// NilUUID is nullable uuid.UUID.
type NilUUID struct {
	Value uuid.UUID
	Null  bool
}

// SetTo sets value to v.
func (o *NilUUID) SetTo(v uuid.UUID) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilUUID) SetToNull() {
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateOrderRequest returns new OptCreateOrderRequest with value set to v.
func NewOptCreateOrderRequest(v CreateOrderRequest) OptCreateOrderRequest {
	return OptCreateOrderRequest{
		Value: v,
		Set:   true,
	}
}

// OptCreateOrderRequest is optional CreateOrderRequest.
type OptCreateOrderRequest struct {
	Value CreateOrderRequest
	Set   bool
}

// IsSet returns true if OptCreateOrderRequest was set.
func (o OptCreateOrderRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateOrderRequest) Reset() {
	var v CreateOrderRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateOrderRequest) SetTo(v CreateOrderRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateOrderRequest) Get() (v CreateOrderRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateOrderRequest) Or(d CreateOrderRequest) CreateOrderRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDeleteOrderRequest returns new OptDeleteOrderRequest with value set to v.
func NewOptDeleteOrderRequest(v DeleteOrderRequest) OptDeleteOrderRequest {
	return OptDeleteOrderRequest{
		Value: v,
		Set:   true,
	}
}

// OptDeleteOrderRequest is optional DeleteOrderRequest.
type OptDeleteOrderRequest struct {
	Value DeleteOrderRequest
	Set   bool
}

// IsSet returns true if OptDeleteOrderRequest was set.
func (o OptDeleteOrderRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDeleteOrderRequest) Reset() {
	var v DeleteOrderRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDeleteOrderRequest) SetTo(v DeleteOrderRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDeleteOrderRequest) Get() (v DeleteOrderRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDeleteOrderRequest) Or(d DeleteOrderRequest) DeleteOrderRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPayOrderRequest returns new OptPayOrderRequest with value set to v.
func NewOptPayOrderRequest(v PayOrderRequest) OptPayOrderRequest {
	return OptPayOrderRequest{
		Value: v,
		Set:   true,
	}
}

// OptPayOrderRequest is optional PayOrderRequest.
type OptPayOrderRequest struct {
	Value PayOrderRequest
	Set   bool
}

// IsSet returns true if OptPayOrderRequest was set.
func (o OptPayOrderRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPayOrderRequest) Reset() {
	var v PayOrderRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPayOrderRequest) SetTo(v PayOrderRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPayOrderRequest) Get() (v PayOrderRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPayOrderRequest) Or(d PayOrderRequest) PayOrderRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order
type Order struct {
	// UUID заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// UUID деталей для заказа.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Общая стоимость заказа.
	TotalPrice float32 `json:"total_price"`
	// UUID транзакции (если оплачен).
	TransactionUUID NilUUID `json:"transaction_uuid"`
	// Способ оплаты (если оплачен).
	PaymentMethod PaymentMethod `json:"payment_method"`
	// Статус заказа.
	Status OrderStatus `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *Order) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *Order) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *Order) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Order) GetTotalPrice() float32 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *Order) GetTransactionUUID() NilUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Order) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *Order) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *Order) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *Order) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Order) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *Order) SetTransactionUUID(val NilUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Order) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

// Payment Method.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELED       OrderStatus = "CANCELED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELED:
		*s = OrderStatusCANCELED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// UUID транзакции.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Payment Method.
// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodUNKNOWN       PaymentMethod = "UNKNOWN"
	PaymentMethodCARD          PaymentMethod = "CARD"
	PaymentMethodSBP           PaymentMethod = "SBP"
	PaymentMethodCREDITCARD    PaymentMethod = "CREDIT_CARD"
	PaymentMethodINVESTORMONEY PaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodUNKNOWN,
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodCREDITCARD,
		PaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodUNKNOWN:
		return []byte(s), nil
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodCREDITCARD:
		return []byte(s), nil
	case PaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodUNKNOWN:
		*s = PaymentMethodUNKNOWN
		return nil
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodCREDITCARD:
		*s = PaymentMethodCREDITCARD
		return nil
	case PaymentMethodINVESTORMONEY:
		*s = PaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/404_not_found
type R404NotFound struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *R404NotFound) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *R404NotFound) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *R404NotFound) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *R404NotFound) SetMessage(val string) {
	s.Message = val
}

func (*R404NotFound) cancelOrderRes() {}
func (*R404NotFound) getOrderRes()    {}
func (*R404NotFound) payOrderRes()    {}

// Ref: #/components/schemas/409_conflict
type R409Conflict struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *R409Conflict) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *R409Conflict) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *R409Conflict) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *R409Conflict) SetMessage(val string) {
	s.Message = val
}

func (*R409Conflict) cancelOrderRes() {}

// Ref: #/components/schemas/422_unprocessable_entity
type R422UnprocessableEntity struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *R422UnprocessableEntity) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *R422UnprocessableEntity) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *R422UnprocessableEntity) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *R422UnprocessableEntity) SetMessage(val string) {
	s.Message = val
}

func (*R422UnprocessableEntity) createOrderRes() {}
